fail_fast: true

repos:
  # prek has build-in pre-commit hooks
  # - repo: "https://github.com/pre-commit/pre-commit-hooks"
  #   rev: v5.0.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  #     - id: check-yaml
  #     - id: check-toml
  #     - id: check-added-large-files
  # this will check typos and fix file automatically, but need to re-add file by using git
  - repo: https://github.com/crate-ci/typos
    rev: v1.36.2
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: pretty staged
        name: pretty staged
        description: pretty.
        entry: pnpm pretty-quick --staged
        language: node
