fail_fast: true

repos:
  - repo: local
    hooks:
      - id: typos
        name: typos
        description: typos.
        entry: typos
        language: system
        types:
          - rust
      - id: pretty
        name: pretty
        description: pretty.
        entry: pnpm pretty-quick --staged
        language: node

      # wait for `running multiple commands` feature to complete (https://github.com/j178/prek/issues/431)
      # cargo fmt
      - id: cargo-fmt-mihomo-rule-parser
        name: cargo fmt mihomo-rule-parser
        description: Format mihomo-rule-parser files with rustfmt.
        entry: cargo fmt --manifest-path mihomo-rule-parser/Cargo.toml -- --check
        language: system
        types:
          - rust
        files: \.rs$
      - id: cargo-fmt-tauri-plugin-mihomo
        name: cargo fmt tauri-plugin-mihomo
        description: Format tauri-plugin-mihomo files with rustfmt.
        entry: cargo fmt --manifest-path tauri-plugin-mihomo/Cargo.toml -- --check
        language: system
        types:
          - rust
        files: \.rs$
      - id: cargo-fmt-src-tauri
        name: cargo fmt src-tauri
        description: Format src-tauri files with rustfmt.
        entry: cargo fmt --manifest-path src-tauri/Cargo.toml -- --check
        language: system
        types:
          - rust
        files: \.rs$

      # cargo check
      - id: cargo-check-mihomo-rule-parser
        name: cargo check mihomo-rule-parser
        description: Check the package for errors.
        entry: cargo check --manifest-path mihomo-rule-parser/Cargo.toml --all
        language: system
        types:
          - rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-check-tauri-plugin-mihomo
        name: cargo check tauri-plugin-mihomo
        description: Check the package for errors.
        entry: cargo check --manifest-path tauri-plugin-mihomo/Cargo.toml --all
        language: system
        types:
          - rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-check-src-tauri
        name: cargo check src-tauri
        description: Check the package for errors.
        entry: cargo check --manifest-path src-tauri/Cargo.toml --all
        language: system
        types:
          - rust
        files: \.rs$
        pass_filenames: false

      # cargo clippy
      - id: cargo-clippy-mihomo-rule-parser
        name: cargo clippy mihomo-rule-parser
        description: Lint rust sources
        entry: cargo clippy --manifest-path mihomo-rule-parser/Cargo.toml --all-targets --all-features --tests --benches -- -D warnings
        language: system
        types:
          - rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy-tauri-plugin-mihomo
        name: cargo clippy tauri-plugin-mihomo
        description: Lint rust sources
        entry: cargo clippy --manifest-path tauri-plugin-mihomo/Cargo.toml --all-targets --all-features --tests --benches -- -D warnings
        language: system
        types:
          - rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy-src-tauri
        name: cargo clippy src-tauri
        description: Lint rust sources
        entry: cargo clippy --manifest-path src-tauri/Cargo.toml --all-targets --all-features --tests --benches -- -D warnings
        language: system
        types:
          - rust
        files: \.rs$
        pass_filenames: false
