fail_fast: true

repos:
  # prek has build-in pre-commit hooks
  # - repo: "https://github.com/pre-commit/pre-commit-hooks"
  #   rev: v5.0.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  #     - id: check-yaml
  #     - id: check-toml
  #     - id: check-added-large-files
  # this will check typos and fix file automatically, but need to re-add file by using git
  - repo: https://github.com/crate-ci/typos
    rev: v1.36.2
    hooks:
      - id: typos
  - repo: local
    hooks:
      # no need because of using typos repo
      # - id: typos-check
      #   name: typos check
      #   description: typos check.
      #   entry: typos
      #   language: system
      #   types:
      #     - rust
      - id: pretty
        name: pretty
        description: pretty.
        entry: pnpm pretty-quick --staged
        language: node

      # wait for `running multiple commands` feature to complete (https://github.com/j178/prek/issues/431)
      # cargo fmt
      - id: cargo-fmt-mihomo-rule-parser
        name: cargo fmt mihomo-rule-parser
        description: Format mihomo-rule-parser files with rustfmt.
        entry: cargo +nightly fmt --manifest-path crates/mihomo-rule-parser/Cargo.toml -- --check
        language: system
        files: ^crates/mihomo-rule-parser/
        types:
          - rust
      - id: cargo-fmt-tauri-plugin-mihomo
        name: cargo fmt tauri-plugin-mihomo
        description: Format tauri-plugin-mihomo files with rustfmt.
        entry: cargo +nightly fmt --manifest-path crates/tauri-plugin-mihomo/Cargo.toml -- --check
        language: system
        files: ^crates/tauri-plugin-mihomo/
        types:
          - rust
      - id: cargo-fmt-src-tauri
        name: cargo fmt src-tauri
        description: Format src-tauri files with rustfmt.
        entry: cargo +nightly fmt --manifest-path src-tauri/Cargo.toml -- --check
        language: system
        files: ^src-tauri/
        types:
          - rust

      # cargo check
      - id: cargo-check-mihomo-rule-parser
        name: cargo check mihomo-rule-parser
        description: Check the package for errors.
        entry: cargo check --manifest-path crates/mihomo-rule-parser/Cargo.toml --all
        language: system
        files: ^crates/mihomo-rule-parser/
        types:
          - rust
        pass_filenames: false
      - id: cargo-check-tauri-plugin-mihomo
        name: cargo check tauri-plugin-mihomo
        description: Check the package for errors.
        entry: cargo check --manifest-path crates/tauri-plugin-mihomo/Cargo.toml --all
        language: system
        files: ^crates/tauri-plugin-mihomo/
        types:
          - rust
        pass_filenames: false
      - id: cargo-check-src-tauri
        name: cargo check src-tauri
        description: Check the package for errors.
        entry: cargo check --manifest-path src-tauri/Cargo.toml --all
        language: system
        files: ^src-tauri/
        types:
          - rust
        pass_filenames: false

      # cargo clippy
      - id: cargo-clippy-mihomo-rule-parser
        name: cargo clippy mihomo-rule-parser
        description: Lint rust sources
        entry: cargo clippy --manifest-path crates/mihomo-rule-parser/Cargo.toml --all-targets --all-features --tests --benches -- -D warnings
        language: system
        files: ^crates/mihomo-rule-parser/
        types:
          - rust
        pass_filenames: false
      - id: cargo-clippy-tauri-plugin-mihomo
        name: cargo clippy tauri-plugin-mihomo
        description: Lint rust sources
        entry: cargo clippy --manifest-path crates/tauri-plugin-mihomo/Cargo.toml --all-targets --all-features --tests --benches -- -D warnings
        language: system
        files: ^crates/tauri-plugin-mihomo/
        types:
          - rust
        pass_filenames: false
      - id: cargo-clippy-src-tauri
        name: cargo clippy src-tauri
        description: Lint rust sources
        entry: cargo clippy --manifest-path src-tauri/Cargo.toml --all-targets --all-features --tests --benches -- -D warnings
        language: system
        files: ^src-tauri/
        types:
          - rust
        pass_filenames: false
