enablePrePostScripts: false
allowBuilds:
  "@parcel/watcher": true
  core-js: true
  edgedriver: false
  es5-ext: true
  esbuild: true
  geckodriver: false
  meta-json-schema: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - dayjs@1.11.21
  - '@tauri-apps/cli-darwin-arm64@3.0.0-alpha.1'
  - '@tauri-apps/cli-darwin-x64@3.0.0-alpha.1'
  - '@tauri-apps/cli-linux-arm-gnueabihf@3.0.0-alpha.1'
  - '@tauri-apps/cli-linux-arm64-gnu@3.0.0-alpha.1'
  - '@tauri-apps/cli-linux-arm64-musl@3.0.0-alpha.1'
  - '@tauri-apps/cli-linux-riscv64-gnu@3.0.0-alpha.1'
  - '@tauri-apps/cli-linux-x64-gnu@3.0.0-alpha.1'
  - '@tauri-apps/cli-linux-x64-musl@3.0.0-alpha.1'
  - '@tauri-apps/cli-win32-arm64-msvc@3.0.0-alpha.1'
  - '@tauri-apps/cli-win32-ia32-msvc@3.0.0-alpha.1'
  - '@tauri-apps/cli-win32-x64-msvc@3.0.0-alpha.1'
  - '@tauri-apps/cli@3.0.0-alpha.1'
