[files]
extend-exclude = [
  "src/assets/*",
  "crates/tauri-plugin-mihomo/permissions/*",
  "crates/tauri-plugin-mihomo/examples/*",
]

[type.svg]
extend-glob = ["*.svg"]
check-file = false

# crates/mihomo-config/src/raw_config.rs - L654
[default.extend-words]
certifactes = "certifactes"
