// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionType } from "./ConnectionType";
import type { DNSMode } from "./DNSMode";
import type { Network } from "./Network";

export type ConnectionMetaData = { network: Network, type: ConnectionType, sourceIP: string, destinationIP: string, sourceGeoIP: Array<string> | null, destinationGeoIP: Array<string> | null, sourceIPASN: string, destinationIPASN: string, sourcePort: string, destinationPort: string, inboundIP: string, inboundPort: string, inboundName: string, inboundUser: string, host: string, dnsMode: DNSMode, uid: number, process: string, processPath: string, specialProxy: string, specialRules: string, remoteDestination: string, dscp: number, sniffHost: string, };
