// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelayHistory } from "./DelayHistory";

export type Extra = { alive: boolean, history: Array<DelayHistory>, };
