// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * mihomo version
 */
export type MihomoVersion = { meta: boolean, version: string, };
