// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxyProvider } from "./ProxyProvider";

export type ProxyProviders = { providers: { [key in string]?: ProxyProvider }, };
