[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-update-controller",
    "allow-update-secret",
    "allow-get-connections",
    "allow-get-version",
    "allow-clean-fakeip",
    "allow-close-all-connections",
    "allow-close-connections",
    "allow-get-groups",
    "allow-get-group-by-name",
    "allow-delay-group",
    "allow-get-proxies-providers",
    "allow-get-providers-proxy-by-name",
    "allow-update-proxies-providers",
    "allow-healthcheck-providers",
    "allow-healthcheck-providers-proxies",
    "allow-get-proxies",
    "allow-get-proxy-by-name",
    "allow-select-node-for-proxy",
    "allow-delay-proxy-by-name",
    "allow-get-rules",
    "allow-get-rules-providers",
    "allow-update-rules-providers",
    "allow-get-base-config",
    "allow-reload-config",
    "allow-patch-base-config",
    "allow-update-geo",
    "allow-restart",
    "allow-upgrade-core",
    "allow-upgrade-ui",
    "allow-upgrade-geo",
    "allow-ws-connect",
    "allow-ws-traffic",
    "allow-ws-memory",
    "allow-ws-connections",
    "allow-ws-logs",
    "allow-ws-send",
    "allow-ws-disconnect",
]
