blank_issues_enabled: false
contact_links:
  - name: 讨论交流 / Communication
    url: https://t.me/clash_verge_rev
    about: 在 Telegram 群组中与其他用户讨论交流 / Communicate with other users in the Telegram group
