// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Connection } from "./Connection";

/**
 * connections
 */
export type Connections = { downloadTotal: bigint, uploadTotal: bigint, connections: Array<Connection> | null, memory: number, };
