// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrutalOption } from "./BrutalOption";

export type MuxOption = { padding?: boolean, brutal?: BrutalOption, };
