// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Proxy } from "./Proxy";

/**
 * proxies
 */
export type Proxies = { proxies: { [key in string]?: Proxy }, };
