// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProxyType = "Direct" | "Reject" | "RejectDrop" | "Compatible" | "Pass" | "Dns" | "Shadowsocks" | "ShadowsocksR" | "Snell" | "Socks5" | "Http" | "Vmess" | "Vless" | "Trojan" | "Hysteria" | "Hysteria2" | "WireGuard" | "Tuic" | "Ssh" | "Mieru" | "AnyTLS" | "Relay" | "Selector" | "Fallback" | "URLTest" | "LoadBalance";
