// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * proxy delay result
 *
 * displays a message if it times out, otherwise it only displays the delay
 */
export type ProxyDelay = { delay: number, };
