// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuleType = "Domain" | "DomainSuffix" | "DomainKeyword" | "DomainRegex" | "GeoSite" | "GeoIP" | "SrcGeoIP" | "IPASN" | "SrcIPASN" | "IPCIDR" | "SrcIPCIDR" | "IPSuffix" | "SrcIPSuffix" | "SrcPort" | "DstPort" | "InPort" | "InUser" | "InName" | "InType" | "ProcessName" | "ProcessPath" | "ProcessNameRegex" | "ProcessPathRegex" | "Match" | "RuleSet" | "Network" | "DSCP" | "Uid" | "SubRules" | "AND" | "OR" | "NOT";
