// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderType } from "./ProviderType";

export type RuleProvider = { behavior: string, format: string, name: string, ruleCount: number, type: ProviderType, updatedAt: string, vehicleType: string, };
