// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleProvider } from "./RuleProvider";

export type RuleProviders = { providers: { [key in string]?: RuleProvider }, };
