// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderType } from "./ProviderType";
import type { RuleBehavior } from "./RuleBehavior";
import type { RuleFormat } from "./RuleFormat";
import type { VehicleType } from "./VehicleType";

export type RuleProvider = { behavior: RuleBehavior, format: RuleFormat, name: string, ruleCount: number, type: ProviderType, updatedAt: string, vehicleType: VehicleType, };
