// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rule } from "./Rule";

/**
 * rules
 */
export type Rules = { rules: Array<Rule>, };
