// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubScriptionInfo = { Upload: number, Download: number, Total: number, Expire: number, };
