import type { ClashMode } from "./ClashMode";
import type { FindProcessMode } from "./FindProcessMode";
import type { GeoXUrl } from "./GeoXUrl";
import type { LogLevel } from "./LogLevel";
import type { TuicServer } from "./TuicServer";
import type { TunConfig } from "./TunConfig";
export type BaseConfig = {
    port: number;
    socksPort: number;
    redirPort: number;
    tproxyPort: number;
    mixedPort: number;
    tun: TunConfig;
    tuicServer: TuicServer;
    ssConfig: string;
    vmessConfig: string;
    authentication: Array<string> | null;
    skipAuthPrefixes: Array<string> | null;
    lanAllowedIps: Array<string> | null;
    lanDisallowedIps: Array<string> | null;
    allowLan: boolean;
    bindAddress: string;
    inboundTfo: boolean;
    inboundMptcp: boolean;
    mode: ClashMode;
    unifiedDelay: boolean;
    logLevel: LogLevel;
    ipv6: boolean;
    interfaceName: string;
    routingMark: number;
    geoxUrl: GeoXUrl;
    geoAutoUpdate: boolean;
    geoUpdateInterval: number;
    geodataMode: boolean;
    geodataLoader: string;
    geositeMatcher: string;
    tcpConcurrent: boolean;
    findProcessMode: FindProcessMode;
    sniffing: boolean;
    globalClientFingerprint: string;
    globalUa: string;
    etagSupport: boolean;
    keepAliveInterval: number;
    keepAliveIdle: number;
    disableKeepAlive: boolean;
};
