[package]
name = "mihomo-config"
version = "0.1.0"
edition = "2024"

[lib]
name = "mihomo_config"

[dependencies]
anyhow = "1.0.99"
indexmap = { version = "2.11.1", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde_yaml_ng = "0.10.0"
