name: "Build for Linux"
branding:
  icon: user-check
  color: gray-dark
inputs:
  target:
    required: true
    description: "Rust Target"
  alpha:
    required: true
    description: "Build Alpha"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.target }}
    - ${{ inputs.alpha }}
