/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as TestImport } from "./routes/test";
import { Route as SettingsImport } from "./routes/settings";
import { Route as RulesImport } from "./routes/rules";
import { Route as ProxiesImport } from "./routes/proxies";
import { Route as ProfilesImport } from "./routes/profiles";
import { Route as LogsImport } from "./routes/logs";
import { Route as ConnectionsImport } from "./routes/connections";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const TestRoute = TestImport.update({
  id: "/test",
  path: "/test",
  getParentRoute: () => rootRoute,
} as any);

const SettingsRoute = SettingsImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRoute,
} as any);

const RulesRoute = RulesImport.update({
  id: "/rules",
  path: "/rules",
  getParentRoute: () => rootRoute,
} as any);

const ProxiesRoute = ProxiesImport.update({
  id: "/proxies",
  path: "/proxies",
  getParentRoute: () => rootRoute,
} as any);

const ProfilesRoute = ProfilesImport.update({
  id: "/profiles",
  path: "/profiles",
  getParentRoute: () => rootRoute,
} as any);

const LogsRoute = LogsImport.update({
  id: "/logs",
  path: "/logs",
  getParentRoute: () => rootRoute,
} as any);

const ConnectionsRoute = ConnectionsImport.update({
  id: "/connections",
  path: "/connections",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/connections": {
      id: "/connections";
      path: "/connections";
      fullPath: "/connections";
      preLoaderRoute: typeof ConnectionsImport;
      parentRoute: typeof rootRoute;
    };
    "/logs": {
      id: "/logs";
      path: "/logs";
      fullPath: "/logs";
      preLoaderRoute: typeof LogsImport;
      parentRoute: typeof rootRoute;
    };
    "/profiles": {
      id: "/profiles";
      path: "/profiles";
      fullPath: "/profiles";
      preLoaderRoute: typeof ProfilesImport;
      parentRoute: typeof rootRoute;
    };
    "/proxies": {
      id: "/proxies";
      path: "/proxies";
      fullPath: "/proxies";
      preLoaderRoute: typeof ProxiesImport;
      parentRoute: typeof rootRoute;
    };
    "/rules": {
      id: "/rules";
      path: "/rules";
      fullPath: "/rules";
      preLoaderRoute: typeof RulesImport;
      parentRoute: typeof rootRoute;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsImport;
      parentRoute: typeof rootRoute;
    };
    "/test": {
      id: "/test";
      path: "/test";
      fullPath: "/test";
      preLoaderRoute: typeof TestImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/connections": typeof ConnectionsRoute;
  "/logs": typeof LogsRoute;
  "/profiles": typeof ProfilesRoute;
  "/proxies": typeof ProxiesRoute;
  "/rules": typeof RulesRoute;
  "/settings": typeof SettingsRoute;
  "/test": typeof TestRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/connections": typeof ConnectionsRoute;
  "/logs": typeof LogsRoute;
  "/profiles": typeof ProfilesRoute;
  "/proxies": typeof ProxiesRoute;
  "/rules": typeof RulesRoute;
  "/settings": typeof SettingsRoute;
  "/test": typeof TestRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/connections": typeof ConnectionsRoute;
  "/logs": typeof LogsRoute;
  "/profiles": typeof ProfilesRoute;
  "/proxies": typeof ProxiesRoute;
  "/rules": typeof RulesRoute;
  "/settings": typeof SettingsRoute;
  "/test": typeof TestRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/connections"
    | "/logs"
    | "/profiles"
    | "/proxies"
    | "/rules"
    | "/settings"
    | "/test";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/connections"
    | "/logs"
    | "/profiles"
    | "/proxies"
    | "/rules"
    | "/settings"
    | "/test";
  id:
    | "__root__"
    | "/"
    | "/connections"
    | "/logs"
    | "/profiles"
    | "/proxies"
    | "/rules"
    | "/settings"
    | "/test";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ConnectionsRoute: typeof ConnectionsRoute;
  LogsRoute: typeof LogsRoute;
  ProfilesRoute: typeof ProfilesRoute;
  ProxiesRoute: typeof ProxiesRoute;
  RulesRoute: typeof RulesRoute;
  SettingsRoute: typeof SettingsRoute;
  TestRoute: typeof TestRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  LogsRoute: LogsRoute,
  ProfilesRoute: ProfilesRoute,
  ProxiesRoute: ProxiesRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  TestRoute: TestRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/connections",
        "/logs",
        "/profiles",
        "/proxies",
        "/rules",
        "/settings",
        "/test"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/connections": {
      "filePath": "connections.tsx"
    },
    "/logs": {
      "filePath": "logs.tsx"
    },
    "/profiles": {
      "filePath": "profiles.tsx"
    },
    "/proxies": {
      "filePath": "proxies.tsx"
    },
    "/rules": {
      "filePath": "rules.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
