pub mod autostart;
pub mod dirs;
pub mod format;
pub mod help;
pub mod i18n;
pub mod init;
#[cfg(target_os = "linux")]
pub mod linux;
pub mod network;
pub mod notification;
pub mod resolve;
pub mod server;
pub mod singleton;
pub mod tmpl;
pub mod window_manager;
