#[cfg(target_os = "macos")]
pub mod connections_stream;
pub mod dirs;
pub mod help;
pub mod init;
#[cfg(target_os = "linux")]
pub mod linux;
pub mod network;
pub mod notification;
pub mod resolve;
#[cfg(target_os = "windows")]
pub mod schtasks;
pub mod server;
pub mod singleton;
pub mod speed;
pub mod tmpl;
#[cfg(target_os = "macos")]
pub mod tray_speed;
pub mod window_manager;
