name: Cargo Audit

on:
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  audit:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run Cargo Audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.WORKFLOW_AUDIT_TOKEN }}
